---
- name: create privileged groups
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ priv_groups }}"

- name: create regular groups
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ regular_groups }}"

- name: create and add users in groups
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.gr }}"
  loop: "{{ users }}" 

- name: Assign root privileges to specific users
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ item }}" 
    validate: /usr/sbin/visudo -cf %s
  loop:
    - "Alex ALL=(ALL) NOPASSWD:ALL"
    - "Bob ALL=(ALL) NOPASSWD:ALL"
    - "Cristi ALL=(ALL) NOPASSWD:ALL"

- name: Add public SSH keys for the users as authorized keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '/home/ansible/new/roles/create_users/files/key.pub') }}"
    path: "{{ item.path }}"
  loop: "{{ users }}"
