---
- name: create regular groups
  group:
    name: "{{ item }}"
    state: present
  loop: "{{ regular_groups }}"

- name: create and add users in groups
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.gr }}"
  loop: "{{ users }}" 

- name: Add public SSH keys for the users as authorized keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', '/home/ansible/new/roles/users_task4/files/key.pub') }}"
    path: "{{ item.path }}"
  loop: "{{ users }}"
